//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingHelper.Core.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserInRole> UserInRole { get; set; }
        public virtual DbSet<TrainingProgram> TrainingProgram { get; set; }
        public virtual DbSet<MadeExerciseFromProgram> MadeExerciseFromProgram { get; set; }
        public virtual DbSet<MadeExercises> MadeExercises { get; set; }
        public virtual DbSet<MadeSeries> MadeSeries { get; set; }
        public virtual DbSet<TrainingExercise> TrainingExercise { get; set; }
        public virtual DbSet<UserToProgram> UserToProgram { get; set; }
        public virtual DbSet<TrainingProgramToExercise> TrainingProgramToExercise { get; set; }
    }
}
