//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingHelper.Core.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MadeExerciseFromProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MadeExerciseFromProgram()
        {
            this.MadeSeries = new HashSet<MadeSeries>();
        }
    
        public int Id { get; set; }
        public int ExerciceToProgramId { get; set; }
        public System.DateTime Date { get; set; }
        public string AdditionalInfos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MadeSeries> MadeSeries { get; set; }
        public virtual TrainingProgramToExercise TrainingProgramToExercise { get; set; }
    }
}
