//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingHelper.Core.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MadeSeries
    {
        public int Id { get; set; }
        public Nullable<int> MadeExerciseFromProgramId { get; set; }
        public Nullable<int> MadeExerciseId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Repetition { get; set; }
        public string AdditionallInfos { get; set; }
    
        public virtual MadeExerciseFromProgram MadeExerciseFromProgram { get; set; }
        public virtual MadeExercises MadeExercises { get; set; }
    }
}
