//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingHelper.Core.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgramToExercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingProgramToExercise()
        {
            this.MadeExerciseFromProgram = new HashSet<MadeExerciseFromProgram>();
        }
    
        public int Id { get; set; }
        public int ProgramId { get; set; }
        public int ExerciseId { get; set; }
        public Nullable<int> SerieObjective { get; set; }
        public Nullable<int> RepetitionObjetive { get; set; }
        public Nullable<System.TimeSpan> TimeBetweenSeries { get; set; }
        public Nullable<System.TimeSpan> TimeAfterSeries { get; set; }
        public Nullable<System.TimeSpan> TimeObjetive { get; set; }
        public string AdditionalInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MadeExerciseFromProgram> MadeExerciseFromProgram { get; set; }
        public virtual TrainingExercise TrainingExercise { get; set; }
        public virtual TrainingProgram TrainingProgram { get; set; }
    }
}
